name: "🐞 Bug report"
description: File a bug report
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue.

        Please fill out the following form as detailed as possible to help us fix the bug.
  - type: checkboxes
    attributes:
      label: Checks
      description: Before posting a report, make sure you have searched for duplicates.
      options:
        - label: "Not a duplicate."
          required: true
  - type: input
    validations:
      required: true
    attributes:
      label: Version
      description: The version of smooth-scrollbar.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Description
      description: Describe the bug and the expected behavior.
      placeholder: |
        **Summary**
        ...

        **Expected Behavior**
        ...
  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps to Reproduce
      description: Tell us how to reproduce it.
      placeholder: |
        1. ...
        2. ...
  - type: input
    attributes:
      label: Online Demo
      description: Provide a URL to an online demo that reproduces the bug. (Optional but recommended)
      placeholder: "https://codesandbox.io/s/your-project"
